---
minimum_pre_commit_version: 3.3.0
default_install_hook_types: [pre-commit,commit-msg]

repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []